### Gateway health
GET http://localhost:3000/health

### QCMs via gateway
GET http://localhost:3000/api/qcms

### Via le gateway — Créer un QCM
POST http://localhost:3000/api/qcms
Content-Type: application/json

{
  "data": {
    "name": "Michael Jackson",
    "questions": [
      {
        "description": "Quel surnom était donné à Michael Jackson ?",
        "propositions": [
          { "description": "The King of Pop", "isValid": true },
          { "description": "The King of Rock", "isValid": false },
          { "description": "The King of Jazz", "isValid": false }
        ]
      },
      {
        "description": "Quelles chansons sont de Michael Jackson ?",
        "propositions": [
          { "description": "Billie Jean", "isValid": true },
          { "description": "Thriller", "isValid": true },
          { "description": "Shape of You", "isValid": false }
        ]
      },
      {
        "description": "Dans quel groupe Michael Jackson a-t-il commencé sa carrière ?",
        "propositions": [
          { "description": "The Jackson 5", "isValid": true },
          { "description": "ABBA", "isValid": false },
          { "description": "The Beatles", "isValid": false }
        ]
      },
      {
        "description": "Quels albums ont été publiés par Michael Jackson ?",
        "propositions": [
          { "description": "Thriller", "isValid": true },
          { "description": "Bad", "isValid": true },
          { "description": "Nevermind", "isValid": false }
        ]
      }
    ]
  }
}

###Soumettre une reponse
POST http://localhost:3000/api/qcms/1/response
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJtYXgtbG9naW5AdGVzdC5mciIsImlhdCI6MTc4MDQwNzczMywiZXhwIjoxNzgwNDE0OTMzfQ.wnXaS5AjcDKCty63ybKAy6J0ATn4QtP77JOiHp33Q2k

{
  "data": {
    "propositionId": 2,
    "isChecked": true
  }
}

### Register
POST http://localhost:3000/api/auth/local/register
Content-Type: application/json

{
  "data": {
    "firstname": "toto",
    "email": "toto-login@test.fr",
    "password": "koko"
  }
}

### Login
POST http://localhost:3000/api/auth/local/
Content-Type: application/json

{
  "data": {
    "email": "max-login@test.fr",
    "password": "koko"
  }
}

### Login
GET http://localhost:3000/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJtYXgtbG9naW5AdGVzdC5mciIsImlhdCI6MTc4MDQwOTg5MCwiZXhwIjoxNzgwNDE3MDkwfQ.r44XRiSqUONhe7e5P0zTBDzet76l31vUVFrcvjl7p6I




###Soumettre une reponse
GET  http://localhost:3000/api/qcms/1/result
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJtYXgtbG9naW5AdGVzdC5mciIsImlhdCI6MTc4MDQwOTg5MCwiZXhwIjoxNzgwNDE3MDkwfQ.r44XRiSqUONhe7e5P0zTBDzet76l31vUVFrcvjl7p6I

