### GET propositions
GET http://localhost:3001/responses


### GET cat by id
GET http://localhost:3001/results/1

###Creer un qcm
POST http://localhost:3001/results
Content-Type: application/json

{
  "data": {
    "description": "Chrome",
    "isValid": false,
    "questionId": 2
  }
}
