### Register
POST http://localhost:3001/auth/register
Content-Type: application/json

{
  "data": {
    "firstname": "Sabrina",
    "email": "sabrina-login@test.fr",
    "password": "kiki"
  }
}

### Login
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "data": {
    "email": "sabrina-login@test.fr",
    "password": "kiki"
  }
}

